### ISSUE TITLE
Nichts geht mehr, nach FF35 Update

### ISSUE THREAD

**Issue by PeterDre** [BastianKanaan/GMscripts_MyFreeFarm#37]
Nach dem Update auf FF35 funktioniert der Berater überhaupt nicht mehr.
Folgerichtig tut auch der Automat nichts mehr.

Ohne Scripte wurden alle Ackerflächen bebaut bzw. Produktionsstätten in betrieb gesetzt.

Mit Script werden alle Acker LEER angezeigt und Produktionsstätten lassen sich nicht öffnen.
Ebenso wirkungslos die Schnell-Sprungleiste sowie der "Traktor".

CSS-Fehler ???

**Comment by BastianKanaan** [comment]
Duplicate to #36
