### ISSUE TITLE
Script does not work after install

### ISSUE THREAD

**Issue by hamed14768** [BastianKanaan/GMscripts_MyFreeFarm#51]
hi ...
when i install myfreefarm scripts show this log ...

![capture7](https://cloud.githubusercontent.com/assets/11361989/8765537/45e984bc-2e25-11e5-85f7-e2dc1f7cb914.JPG)

please help me to solve this problem .
thank you

**Comment by BastianKanaan** [comment]
Problem occurs if script is installed freshly.
Log:
- Error explode:
str=null debugName=do_main/valMinRack defaultReturn=;
;
Argument is undefined.
- Error do_main:
;
err_trace=Container - headercontainer;
ERROR in function 'explode'
- Error do_main:
;
err_trace=loading;
TypeError: unsafeData.ALL_SLOTS is undefined
- Information start_script:
;
Page=http://sX.myfreefarm.de/main.php?ref=;
Userscript "MyFreeFarm Automat" has started

**Comment by hamed14768** [comment]
So what should I do?

**Comment by hamed14768** [comment]
what i should do to this problem is solved ?

**Comment by MoeLa** [comment]
You could try to install an older version (e.g. Adviser 2.5.0) and set your account(s) up. Then, you upgrade to the current version.

**Comment by hamed14768** [comment]
i install 2.4.2 from openuserjs.org then upgrade to 2.5.3 . but not work :(

**Comment by MoeLa** [comment]
There is a special forum/board for issues like your's: http://myfreefarm-berater.forumprofi.de/index.php Maybe they can help you there. You should further provide information like Lanuage, Greasemonkey- and Firefox-Version. Have you exchanged/upgraded the MyFreeFarm_Common_functions.user.js, too?

**Comment by hamed14768** [comment]
i go to this forum : http://myfreefarm-berater.forumprofi.de/index.php
nobody can't help me .
i install -> GM 3.2 & automat 2.5.3 & berater 2.5.3 & MyFreeFarm_Common_functions 2.5.3 & firefox 35,37,39
i used Persian Myfreefarm and used Eng language .
but not work ... :(

**Comment by MoeLa** [comment]
The script author @BastianKanaan has flagged this thread as an issue to be solved. Now you can only wait until it has been resolved. But if/when there is a work around found, you'll find it in that forum.

**Comment by hamed14768** [comment]
thank you sooooo much ...
i wait until script author @BastianKanaan has been resolved it .
i hope that this problem resolved very soon .
